// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID            int64            `json:"id"`
	Name          pgtype.Text      `json:"name"`
	Avatar        pgtype.Text      `json:"avatar"`
	IsGroup       pgtype.Bool      `json:"is_group"`
	LastMessageID pgtype.Int8      `json:"last_message_id"`
	LastMessageAt pgtype.Timestamp `json:"last_message_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Message struct {
	ID             int64            `json:"id"`
	ConversationID int64            `json:"conversation_id"`
	SenderID       string           `json:"sender_id"`
	Content        pgtype.Text      `json:"content"`
	Type           pgtype.Text      `json:"type"`
	ReplyToID      pgtype.Int8      `json:"reply_to_id"`
	IsDeleted      pgtype.Bool      `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	FileName       pgtype.Text      `json:"file_name"`
	FileID         pgtype.Text      `json:"file_id"`
	FilePath       pgtype.Text      `json:"file_path"`
	FileType       pgtype.Text      `json:"file_type"`
	FileSize       pgtype.Int8      `json:"file_size"`
}

type Participant struct {
	ConversationID    int64            `json:"conversation_id"`
	UserID            string           `json:"user_id"`
	Role              pgtype.Text      `json:"role"`
	JoinedAt          pgtype.Timestamp `json:"joined_at"`
	LastReadMessageID pgtype.Int8      `json:"last_read_message_id"`
}
