// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	GetConversationByID(ctx context.Context, id int64) (Conversation, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]Message, error)
	GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) (int64, error)
	ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]ListConversationsByUserRow, error)
	ListParticipantsByConversation(ctx context.Context, conversationID int64) ([]ListParticipantsByConversationRow, error)
	MarkMessageAsRead(ctx context.Context, arg MarkMessageAsReadParams) error
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	UpdateConversationInfo(ctx context.Context, arg UpdateConversationInfoParams) error
	UpdateConversationLastMessage(ctx context.Context, arg UpdateConversationLastMessageParams) error
	UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) error
}

var _ Querier = (*Queries)(nil)
